### ISSUE TITLE
missing permission for action: SIDEBAR_ELEMENT_CREATE

### ISSUE THREAD

**Issue by seldebrings** [GraphCMS/management-sdk#19]
Hi,

I can't run any migrations anymore in my account,  when I try while i'm logged in, I get this error message: 
**missing permission for action: SIDEBAR_ELEMENT_CREATE**
I have all management API permissions checked.
Same migration worked fine a couple of weeks ago.

**Comment by belazer** [comment]
Hey @seldebrings,

can you please make sure you enable these permissions for the management API?

First click on Edit Permissions:
![Bildschirmfoto 2022-01-26 um 11 00 23](https://user-images.githubusercontent.com/9197688/151142693-09c9be48-3311-47b9-ad06-94b459f81371.png)
The CMD/CTRL + F for sidebar and enable these:
![image](https://user-images.githubusercontent.com/9197688/151142684-6901b0fa-81c7-40e8-af2e-0f0246249ed8.png)

**Comment by feychenie** [comment]
A fix has been released and separate sidebar permissions are not needed anymore.
